---
sidebar: sidebar
permalink: concept-agents.html
keywords: concept, connectors, learn about connectors, what are connectors, what is a connector, what's a connector, days, 14 days, when is an agent required, agent supported locations, restricted mode, private mode, dark site, permissions, multiple agents, disaster recovery, agents, multiple agents, what is a Console agent
summary: You use a Console agent to connect NetApp Console to your infrastructure and securely orchestrate storage solutions across AWS, Azure, Google Cloud, or on-premises environments, as well as use data protection servicers.   
---

= Learn about NetApp Console agents
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You use a Console agent to connect NetApp Console to your infrastructure and securely orchestrate storage solutions across AWS, Azure, Google Cloud, or on-premises environments, as well as use data protection services.  

A Console agent enables you to:

* Orchestrate storage management tasks from the NetApp Console such as provisioning Cloud Volumes ONTAP, setting up storage volumes, using data classification, and more.
* Authenticate using your cloud provider's IAM roles for subscription billing integration
* Use advanced data services (NetApp Backup and Recovery, NetApp Disaster Recovery, NetApp Ransomware Resilience, and NetApp Cloud Tiering)


If you don't need advanced orchestration or data protection services, you can centrally manage on-premises ONTAP clusters and cloud-native storage services without deploying an agent. Some monitoring and data mobility tools are also available without an agent.

The following table shows which features and services you can use with and without a Console agent.


[cols=3*,options="header",cols="40,20a,20a",width="100%"]
|===
|  | Available with agent| Available without agent
3+| *Supported Storage systems*:


| Amazon FSx for ONTAP| Yes (discovery and management features) | Yes (discovery only)
| Amazon S3 storage | Yes | No
| Azure Blob storage | Yes | Yes
| Azure NetApp Files | Yes | Yes
| Cloud Volumes ONTAP | Yes | No
| E-Series systems | Yes | No
| Google Cloud NetApp Volumes| Yes | Yes
| Google Cloud storage buckets | Yes | No
| StorageGRID systems | Yes | No
| On-premises ONTAP cluster  (advanced management and discovery) | Yes (advanced management and discovery) | No (basic discovery only)
3+| *Storage management and health services*:
| Alerts | Yes | No
| Automation hub | Yes| Yes
| Digital Advisor (Active IQ) | Yes | No
| License and subscription management  | Yes | No
| Economic efficiency | Yes | No
| Home page dashboard metrics | Yes^2^ | No
| Lifecycle planning | Yes | No^1^
| Sustainability | Yes | No
| Software updates | Yes  | Yes
| NetApp Workloads | Yes | Yes

3+| *Available data services*:
| NetApp Backup and Recovery | Yes | No
| NetApp Data Classification | Yes | No
| NetApp Cloud Tiering | Yes | No
| NetApp Copy and Sync | Yes | No
| NetApp Disaster Recovery | Yes | No
| NetApp Ransomware Resilience | Yes | No
| NetApp Volume Caching | Yes | No



|===

^1^ You can view Lifecycle planning without a Console agent, but a Console agent is required to initiate actions.

^2^ Accurate metrics on the Home page require appropriately sized and configured Console agents.



[[agents-must-be-operational-at-all-times]]
== Console agents must be operational at all times

Console agents are a fundamental part of the NetApp Console. It's your responsibility (the customer) to ensure that relevant agents are up, operational, and accessible at all times. The Console can handle short agent outages, but you must fix infrastructure failures quickly.

This documentation is governed by the EULA. Operating the product outside the documentation may impact its functionality and your EULA rights.


== Supported locations

You can install agents in the following locations:

* Amazon Web Services

* Microsoft Azure
+
Deploy a Console agent in Azure in the same region as the Cloud Volumes ONTAP systems it manages. Alternatively, deploy it in the https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies[Azure region pair^]. This ensures that an Azure Private Link connection is used between Cloud Volumes ONTAP and its associated storage accounts. https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-enabling-private-link.html[Learn how Cloud Volumes ONTAP uses an Azure Private Link^]

* Google Cloud
+
To use the Console and data services with Google Cloud, deploy your agent in Google Cloud.

* On your premises

== Communication with cloud providers

The agent uses TLS 1.3 for all communication to AWS, Azure, and Google Cloud.
 

[[agent-installation]]
== How to install a Console agent

You can install a Console agent directly from the Console, from your cloud provider's marketplace, or by manually installing the software on your own Linux host or in your VCenter environment.

* link:concept-modes.html[Learn about NetApp Console deployment modes]
* link:task-quick-start-standard-mode.html[Get started with NetApp Console in standard mode]
* link:task-quick-start-restricted-mode.html[Get started with NetApp Console in restricted mode]


== Cloud provider permissions

You need specific permissions to create the Console agent directly from the NetApp Console and another set of permissions for the Console agent itself. If you create the Console agent in AWS or Azure directly from the Console, then the Console creates the Console agent with the permissions that it needs.

When using the Console in standard mode, how you provide permissions depends on how you plan to create the Console agent.

To learn how to set up permissions, refer to the following:

* Standard mode
** link:concept-install-options-aws.html[Agent installation options in AWS]
** link:concept-install-options-azure.html[Agent installation options in Azure]
** link:concept-install-options-google.html[Agent installation options in Google Cloud]
** link:task-install-agent-on-prem.html#agent-permission-aws-azure[Set up cloud permissions for on-premises deployments]
* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions[Set up permissions for restricted mode]


To view the exact permissions that the Console agent needs for day-to-day operations, refer to the following pages:

* link:reference-permissions-aws.html[Learn how the Console agent uses AWS permissions]
* link:reference-permissions-azure.html[Learn how the Console agent uses Azure permissions]
* link:reference-permissions-gcp.html[Learn how the Console agent uses Google Cloud permissions]

It's your responsibility to update the Console agent policies as new permissions are added in subsequent releases. The release notes list new permissions.

== Agent upgrades

NetApp updates agent software monthly to add features and improve stability. Some Console features, like Cloud Volumes ONTAP and on-premises ONTAP cluster management, rely on the Console agent version and settings.

When you install your agent in the cloud, the Console agent updates automatically if it has internet access. 


== Operating system and VM maintenance

include::_include/vm-maintenance.adoc[]

<<agents-must-be-operational-at-all-times,The Console agent must be operational at all times>>.

== Multiple systems and agents

An agent can manage multiple systems and support data services in the Console. You can use a single agent to manage multiple systems based on deployment size and the data services you use.

For large-scale deployments, work with your NetApp representative to size your environment. Contact NetApp Support if you experience issues.



Here are a few examples of agent deployments:

* You have a multicloud environment (for example, AWS and Azure) and you prefer to have one agent in AWS and another in Azure. Each manages the Cloud Volumes ONTAP systems running in those environments.

* A service provider might use one Console organization to provide services for their customers, while using another organization to provide disaster recovery for one of their business units. Each organization needs its own agent.