---
sidebar: sidebar
permalink: reference-agent-maint-console-config-checker.html
keywords: transparent proxy, connector certificate, agent maintenance console, proxy configuration, connector proxy. agent proxy
summary: You can use the Console agent maintenance console to configure a Console agent to use a transparent proxy server.
---

= Agent validation with the maintenance console
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the Console agent maintenance console to validate the configuration of a Console agent.

== Access the agent maintenance console
You can access the maintenance Console from the Console agent host. Navigate to the following directory:
[source,cli]
----
/opt/application/netapp/service-manager-2/agent-maint-console
----

== View help for any command
To view help for any command, append `--help` to the command. For example, to view help for the `proxy add` command, use the following command: 
[source,cli]
----    
./agent-maint-console config-checker --help
----

== config-checker validate

The `config-checker validate` command allows you to validate the configuration of a Console agent. 


=== Parameters
`--services <comma-separated list of services to validate>` --*REQUIRED*--
[role="quick-margin-para"]
Choose one or more services to validate. Valid service names are: 

* `PLATFORM` which validates network connectivity to required Console endpoints.

`--validationTypes <comma-separated list validation types to run>` --*REQUIRED*--
[role="quick-margin-para"]
Choose from one or more validation types to run. Valid validation types are:

* `NETWORK` which validates network connectivity to required Console endpoints.

`--proxy <url>` --*OPTIONAL*--
[role="quick-margin-para"]
Specifies the proxy server URL to use for the validation. Required if your agent is configured to use a proxy server.

`--certs <paths>` --*OPTIONAL*--
[role="quick-margin-para"]  
Specifies the path to one or more certificate files to use for the validation. The certificate files must be in PEM format. Separate multiple paths with commas. This parameter is required if your agent uses a custom certificate.




=== Config-checker validate examples

.Basic validation:
[role="quick-margin-para"]
[source,cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK
----

.Validation where a proxy server is used for the agent:
[role="quick-margin-para"]
[source,cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypeS NETWORK --proxy http://proxy.company.com:8080
----

.Validation where a certificate is used for the agent:
[role="quick-margin-para"]
[source,cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK --certs /path/to/cert1.pem,/path/to/cert2.pem
----

.View the status of the last configuration check
[role="quick-margin-para"]
[source,cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypeS NETWORK --proxy http://proxy.company.com:8080
----

== config-checker status

The `config-checker status` command allows you to view the status of the last configuration check that was run on the Console agent.

=== Parameters
`--v ` or '--verbose' --*OPTIONAL*--

[role="quick-margin-para"]
Provides detailed information about the last configuration check.


=== Config-checker status example
[source,cli]
----
./agent-maint-console config-checker status --v
----


