---
sidebar: sidebar
permalink: reference-agent-maint-console-config-checker.html
keywords: transparent proxy, connector certificate, agent maintenance console, proxy configuration, connector proxy. agent proxy
summary: You can use the Console agent maintenance console to configure a Console agent to use a transparent proxy server.
---

= Console agent validation with the maintenance console in NetApp Console
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the Console agent maintenance console to validate the installation and configuration of a Console agent.

== Access the agent maintenance console
You can access the maintenance Console from the Console agent host. Navigate to the following directory:
[source,cli]
----
/opt/application/netapp/service-manager-2/agent-maint-console
----


== config-checker validate

The `config-checker validate` command allows you to validate the configuration of a Console agent. 


=== Parameters
`--services <comma-separated list of services to validate>` --*REQUIRED*--
[role="quick-margin-para"]
Choose one or more services to validate. Valid service names are: 

*`PLATFORM` which validates network connectivity to required Console endpoints as well as if the required ports are open for the Console agent.


`--validationTypes <comma-separated list validation types to run>` --*REQUIRED*--
Choose from one or more validation types to run. Valid validation types are:

* `NETWORK` which validates network connectivity to required Console endpoints.
* `HARDWARE` which validates that the agent host meets the minimum hardware requirements for the Console agent. 

`--proxy <url>` --*OPTIONAL*--
[role="quick-margin-para"]
Specifies the proxy server URL to use for the validation. Required if your agent is configured to use a proxy server.

`--certs <paths>` --*OPTIONAL*--
[role="quick-margin-para"]  
Specifies the path to one or more certificate files to use for the validation. The certificate files must be in PEM format. Separate multiple paths with commas. This parameter is required if your agent uses a custom certificate.


=== Config-checker validate examples
The following examples include validating network connectivity, required ports, and hardware requirments along with different combinations of using a proxy server and custom certificates.

.Validation for network connectivity and hardware requirements:
[role="quick-margin-para"]
[source,cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE
----

.Validation where a proxy server is used for the agent:
[role="quick-margin-para"]
[source,cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE --proxy http://proxy.company.com:8080
----

.Validation where a certificate is used for the agent:
[role="quick-margin-para"]
[source,cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE --certs /path/to/cert1.pem,/path/to/cert2.pem
----


=== View help for any command
To view help for any command, append `--help` to the command. For example, to view help for the `proxy add` command, use the following command:

[source,cli]
----
./agent-maint-console proxy add --help
----

