---
sidebar: sidebar
permalink: reference-agent-maint-console-proxy.html
keywords: transparent proxy, connector certificate, agent maintenance console, proxy configuration, connector proxy, agent proxy
summary: You can use the Console agent maintenance console to configure a Console agent to use a transparent proxy server.
---

= Transparent proxy commands for the Console agent in NetApp Console 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the Console agent maintenance console to configure a Console agent to use a transparent proxy server.


== Access the agent maintenance console
You can access the maintenance console from the Console agent host. Navigate to the following directory:

[source,cli]
----
/opt/application/netapp/service-manager-2/agent-maint-console
----

=== View help for any command
To view help for any command, append `--help` to the command. For example, to view help for the `proxy add` command, use the following command: 

[source,cli]
----
./agent-maint-console proxy add --help
----

== proxy get

The `proxy get` command displays information about the current transparent proxy server configuration. To view the current transparent proxy server configuration, use the following command:

=== Proxy get example

[source,cli]
----
./agent-maint-console proxy get
----

== proxy add
The `proxy add` command configures the agent to use a transparent proxy server.


=== Parameters
`-c <certificate file>`
[role="quick-margin-para"]
Specifies the path to the certificate file for the proxy server. The certificate file must be in PEM format. Ensure that the certificate file is in the same directory as the command or specify the full path to the certificate file. 

=== Proxy add example

To add a transparent proxy server, use the following command, where `/home/ubuntu/myCA1.pem` is the path to the certificate file for the proxy server. The certificate file must be in PEM format:
[source,cli]
----
./agent-maint-console proxy add -c /home/ubuntu/myCA1.pem
----

== proxy update
The `proxy update` command allows you to update the certificate of a transparent proxy.

=== Parameters

`-c <certificate file>` specifies the path to the certificate file for the proxy server. The certificate file must be in PEM format.

Ensure that the certificate file is in the same directory as the command or specify the full path to the certificate file. 

=== Proxy update example

To update the certificate for a transparent proxy server, use the following command, where `/home/ubuntu/myCA1.pem` is the path to the new certificate file for the proxy server. The certificate file must be in PEM format: 
[source,cli]
----
./agent-maint-console proxy update -c /home/ubuntu/myCA1.pem
----

== proxy remove
The `proxy remove` command removes the transparent proxy server configuration from the agent.

=== Proxy remove example
To remove the transparent proxy server, use the following command:
[source,cli]
----
./agent-maint-console proxy remove
----
