---
sidebar: sidebar
permalink: reference-iam-platform-roles.html
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management, bluexp
summary: Assign platform roles to users to grant permissions to manage the NetApp Console, assign roles, add users, create Console agents, and manage federations.
---

= NetApp Console platform access roles
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Assign platform roles to users to grant permissions to manage the NetApp Console, assign roles, add users, create Console agents, and manage federations.

.Example for organization roles for a large multi-national organization
XYZ Corporation organizes data storage access by region—North America, Europe, and Asia-Pacific—providing regional control with centralized oversight.

The *Organization admin* in XYZ Corporation's Console creates an initial organization and separate folders for each region. The *Folder or project admin* for each region organizes projects (with associated resources) within the region's folder.

Regional admins with the *Folder or project admin* role actively manage their folders by adding resources and users. These regional admins can also add, remove, or rename folders and projects they manage. The *Organization admin* inherits permissions for any new resources, maintaining visibility of storage usage across the entire organization.

Within the same organization, one user is assigned the *Federation admin* role to manage the federation of the organization with their corporate IdP. This user can add or remove federated organizations, but cannot manage users or resources within the organization. The *Organization admin* assigns a user the *Federation viewer* role to check federation status and view federated organizations.

The following tables indicate the actions that each Console platform role can perform.




[organization-admin-roles]
== Organization administration roles 
[cols="2,1,1",options="header"]
|===

| Task
| Organization admin
| Folder or project admin


| Create agents | Yes | No 

| Create, modify or delete systems from the Console (add or discover systems) |	Yes | Yes 

| Create folders and projects, including deleting | Yes | No

| Rename existing folders and projects | Yes | Yes 

| Assign roles and add users | Yes | Yes

| Associate resources with folders and projects  | Yes | Yes

| Associate agents with folders and projects  | Yes | No

| Remove agents from folders and projects  | Yes | No

| Manage agents (edit certificates, settings, and so on)  | Yes | No

| Manage credentials from Administration > Credentials  | Yes | Yes
| Create, manage, and view federations | Yes | No
| Register for support and submit cases through the Console | Yes |	Yes 
| Use data services that are not associated with an explicit access role | Yes | Yes 
| View the Audit page and notifications | Yes |	Yes 

|===

[federation-roles]
== Federation roles
[cols="2,1,1",options="header"]
|===

| Task
| Federation admin
| Federation viewer


| Create a federation | Yes | No 

| Verify a domain |	Yes | No

| Add a domain to a federation | Yes | No

| Disable and delete federations | Yes | No

| Test federations | Yes | No

| View federations and their details  | Yes | Yes

|===

[partnership-roles]
== Partnership roles

[cols="2,1,1",options="header"]
|===

| Task
| Partnership admin
| Partnership viewer


| Can create a partnership | Yes | No
| Assign roles to partner members | Yes | No 

| Can add members to a partnership |	Yes | No

| Can view organization partnership details | Yes | Yes


|===


[[super-admin-roles]]
== Super admin and viewer roles 

The Super admin role is for users needing full access to Console features, data services, and storage resources. These users can administer every aspect of the organization, including creating and managing organizations, folders, projects, and resources. They also have the ability to manage users and assign roles across the organization, ensuring proper governance and security. Super admins configure data services, adjust storage, and manage Console agents, maintaining operational efficiency and oversight.

The Super viewer role provides users read-only access to Console features and resources. These users can view organizations, folders, projects, storage resources, and data service configurations, but cannot make any changes. This role is ideal for auditors, compliance officers, or stakeholders who require visibility into the environment without administrative privileges.


.Example for super roles
XYZ Corporation leverages the flexibility of role assignment by granting Super admin access to specific users for particular projects or folders, rather than the entire organization. For example, a user may be given Super admin rights for the "Europe Storage" folder, enabling them to fully manage resources and users within that scope, while retaining limited or viewer access elsewhere. Similarly, a user can be assigned Super viewer access to a specific project, allowing them to monitor its resources without the ability to modify them.

By using Super admin and Super viewer roles with scoped assignments, XYZ Corporation achieves both robust security and operational flexibility, ensuring that users have the appropriate level of access for their responsibilities.


[cols="2,1",options="header"]
|===

| Role
| Inherited roles
|Super admin | Organization admin, Folder or project admin, Federation admin, Partnership admin, Ransomware Resilience admin, Disaster recovery admin, Disaster recovery failover admin, Disaster recovery application admin, Backup admin, Restore admin, Clone admin, Backup super admin, Storage admin, System health specialist, Operations system analyst, Keystone admin, Google Cloud NetApp Volumes admin
|Super viewer | Organization viewer, Federation viewer, Partnership viewer, Ransomware Resilience viewer, Disaster recovery viewer, Backup viewer, Storage viewer, Keystone viewer, Google Cloud NetApp Volumes viewer




|===
