---
sidebar: sidebar
permalink: reference-agent-maint-console.html
keywords: transparent proxy, connector certificate, agent maintenance console, proxy configuration, connector proxy. agent proxy
summary: You can use the Console agent maintenance console to configure a Console agent to use a transparent proxy server.
---

= Console agent maintenance console
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the Console agent maintenance console to configure a Console agent to use a transparent proxy server.

== Access the agent maintenance console
You can access the maintenance Console from the Console agent host. Navigate to the following directory:
[source,CLI]
----
/opt/application/netapp/service-manager-2/agent-maint-console
----

== Transparent proxy commands
The agent maintenance console provides commands to configure the agent to use a transparent proxy server. 

=== View the current transparent proxy configuration
To view the current transparent proxy configuration, use the following command: 
[source,CLI]
----
./agent-maint-console proxy get
----

=== Add a transparent proxy server
To add a transparent proxy server, use the following command, where `/home/ubuntu/myCA1.pem` is the path to the certificate file for the proxy server. The certificate file must be in PEM format:
[source,CLI]
----
./agent-maint-console proxy add -c /home/ubuntu/myCA1.pem
----

Ensure that the certificate file is in the same directory as the command or specify the full path to the certificate file. 

=== Update the certificate for a transparent proxy server
To update the certificate for a transparent proxy server, use the following command, where `/home/ubuntu/myCA1.pem` is the path to the new certificate file for the proxy server. The certificate file must be in PEM format: 
[source,CLI]
----
./agent-maint-console proxy update -c /home/ubuntu/myCA1.pem
----

Ensure that the certificate file is in the same directory as the command or specify the full path to the certificate file. 

=== Remove a transparent proxy server
To remove transparent proxy server, use the following command:
[source,CLI]
----
./agent-maint-console proxy remove
----

=== View help for any command
To view help for any command, append `--help` to the command. For example, to view help for the `proxy add` command, use the following command: 
[source,CLI]
----    
./agent-maint-console proxy add --help
----

