---
sidebar: sidebar
permalink: reference-networking-saas-console-previous.html
keywords: networking, urls, endpoints, web browser, console, network, set up networking, bluexp
summary: When you log in and use the web-based console, it contacts several endpoints to complete the actions that you initiate. Computers that access the NetApp Console must have connections to these endpoints.
---

= Required network access points for 3.9.55 and below
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You need to ensure that the Console and any agents you install have the right network access to function properly. This topic details the network access required for versions of the NetApp Console standard mode 3.9.55 and below, the NetApp Console agent, and NetApp data services outbound internet access and the ability to contact the necessary endpoints.


Set up network access for computers accessing the NetApp Console as Software as a Service (SaaS) and for Console agents installed on-premises or in the cloud. You may also need additional endpoints for certain NetApp data services, including Cloud Volumes ONTAP.

[[update-endpoint-list]]
== Update your endpoint list to the revised list for 4.0.0 and higher
Starting with version 4.0.0, Console agents require fewer endpoints. Existing deployments before 4.0.0 remain supported. After upgrading to 4.0.0 or later, you may remove the old endpoints from your allow list when convenient.

NetApp recommends updating firewall rules to use the revised endpoint list. The revised list is smaller, more secure and easier to manage. NetApp removes the need for wildcard entries, and endpoints for agent upgrades support all data services.

include::_include/endpoints-agent.adoc[tag=endpoints-comparison]


Review complete list of link:reference-networking-saas-console.html[required endpoints for 4.0.0 and higher]

.Steps

. Whitelist the endpoints in link:reference-networking-saas-console.html[Supported endpoints for 4.0.0 and higher].
. Restart the service manager 2 service on each agent by running the following command:

+
[source,cli]
systemctl restart netapp-service-manager.service

. Run the following command and verify that the agent's status shows as _active(running)_:
_
+
[source,cli]
systemctl status netapp-service-manager.service

. Remove the old endpoints from your firewall allow list.



== NetApp endpoints contacted by NetApp Console and Console agents for 3.9.55 and below

Access to the following endpoints is necessary for each computer that accesses the NetApp Console as well as each agent, regardless of where it is deployed.

Additional cloud provider endpoints are needed for Console agents deployed in your respective cloud provider. Cloud provider endpoints are the same for all agent versions.

include::_include/endpoints-agent.adoc[tag=previous-endpoints]



== Cloud provider endpoints contacted by the Console agent 

Cloud provider endpoints are the same for all versions. Review complete list of link:reference-networking-saas-console.html[required endpoints for 4.0.0 and higher]

== Data services endpoints contacted by the Console agent

Some NetApp data services as well as Cloud Volumes ONTAP require the agent to have additional outbound internet access.


=== Endpoints for Cloud Volumes ONTAP

** link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-aws.html#outbound-internet-access-for-cloud-volumes-ontap-nodes[Endpoints for Cloud Volumes ONTAP in AWS]

** link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-azure.html[Endpoints for Cloud Volumes ONTAP in Azure]

** link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-gcp.html#outbound-internet-access[Endpoints for Cloud Volumes ONTAP in Google Cloud]






