---
sidebar: sidebar
permalink: reference-ports-azure.html
keywords: ports, security group, http, https, inbound, outbound
summary: The Azure security group for the agent requires both inbound and outbound rules. The NetApp Console automatically creates this security group when you create a Console agent from the Console. for other installation options, You need to set up this security group manually.
---

= Console agent security group rules in Azure
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Azure security group for the agent requires both inbound and outbound rules. The NetApp Console automatically creates this security group when you create a Console agent from the Console. for other installation options, You need to set up this security group manually.

== Inbound rules

[cols=3*,options="header,autowidth"]
|===

| Protocol
| Port
| Purpose

| SSH | 22 | Provides SSH access to the agent host
| HTTP | 80 a| 
* Provides HTTP access from client web browsers to the local user interface
* Used during the Cloud Volumes ONTAP upgrade process
| HTTPS | 443 | Provides HTTPS access from client web browsers to the local user interface, and connections from the NetApp Data Classification instance
| TCP | 3128 | Provides Cloud Volumes ONTAP with internet access to send AutoSupport messages to NetApp Support. You must manually open this port after deployment. https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-verify-autosupport.html[Learn how the agent is used as a proxy for AutoSupport messages^]

|===

== Outbound rules

The predefined security group for the agent opens all outbound traffic. If that is acceptable, follow the basic outbound rules. If you need more rigid rules, use the advanced outbound rules.

=== Basic outbound rules

The predefined security group for the agent includes the following outbound rules.

[cols=3*,options="header,autowidth"]
|===

| Protocol
| Port
| Purpose

| All TCP | All | All outbound traffic
| All UDP |	All | All outbound traffic

|===

=== Advanced outbound rules

If you need rigid rules for outbound traffic, you can use the following information to open only those ports that are required for outbound communication by the agent.

NOTE: The source IP address is the agent host.

[cols=5*,options="header,autowidth"]
|===

| Service
| Protocol
| Port
| Destination
| Purpose

| API calls and AutoSupport | HTTPS | 443 | Outbound internet and ONTAP cluster management LIF | API calls to Azure, to ONTAP, to NetApp Data Classification, and sending AutoSupport messages to NetApp
| API calls | TCP | 8080 | Data Classification | Probe to Data Classification instance during deployment
| DNS | UDP | 53 | DNS | Used for DNS resolve by the Console

|===
