---
sidebar: sidebar
permalink: task-maintain-agents.html
keywords: agent operating system, agent maintenance, vm maintenance, os updates, operating system updates, stop agent, restart agent, notifications, agent health, agent disk space, agent cpu usage, agent ram usage, agent vm, connector, connector health
summary: Maintaining the operating system on the agent host is your responsibility. For example, you should apply security updates to the operating system on the Console agent host by following your company's standard procedures for operating system distribution.
---

= Maintain the VM for a manually installed Console agent
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
When you manually install a Console agent, maintaining the operating system on the agent host is your (the customer's) responsibility. For example, you (the customer) should apply security updates to the operating system on the agent host by following your company's standard procedures for operating system distribution.


== Apply operating system updates to the agent host

Apply OS security patches without stopping agent host services. 

To maintain compatibility with supported configurations, you should prevent Docker or Podman from being upgraded during routine OS patching. You can do this by either temporarily excluding Docker or Podman during updates or by permanently configuring the package manager to skip Docker or Podman updates.

The following are examples of how to exclude Docker or Podman updates for different Linux distributions. Consult your Linux distribution's documentation for the most up-to-date instructions on how to exclude packages from updates.

.Podman example
[source,bash]
sudo apt-mark hold podman
sudo apt update 
sudo apt upgrade

.Docker example
[source,bash]
sudo dnf update --exclude=docker*


== VM or instance type

If you create a Console agent from the Console, it deploys a VM instance in your cloud provider with a default configuration. After you create the agent, don't switch to a smaller VM instance with less CPU or RAM.

The following table lists the CPU and RAM requirements:

include::_include/os-reqs.adoc[tag=cpu-ram]

link:reference-agent-default-config.html[Learn about the default configuration for the agent].

[[monitor-disk-space]]
== Monitor the agent

The Console notifies you when the agent VM is unhealthy, including disk space, RAM, and CPU issues. Monitor these notifications in the Notifications Center within the Console or configure email notifications. Occasional increases in disk space, memory, or CPU usage are normal, but if it happens frequently, you should take steps to resolve.

For example, the Console notifies you when an agent resource (CPU, RAM, or disk space) exceeds 90% of its total capacity for 30 consecutive minutes. Afterwards, if the resource usage drops below that threshold, the notification displays as resolved (green) in the Notifications Center.


NOTE: Work with NetApp support if you have questions about modifying your agent VM.


link:https://docs.netapp.com/us-en/console-setup-admin/task-monitor-cm-operations.html#notification-center[Learn more.^]

[cols=2*,options="header",cols="47,47",width="95%"]
|===

| Notification
| Action needed

| Disk space is too high | link:https://kb.netapp.com/Cloud/BlueXP/Cloud_Manager/How_to_resolve_disk_space_issues_on_BlueXP_connector_VM[Review the NetApp Knowledge Base article^].
| CPU usage is too high | Increase the CPU size of the agent VM in your cloud provider or on-premises, depending on where you installed it. Alternatively, create additional agents and distribute the workload across multiple agents. RAM utilization can vary based on your environment, ONTAP workloads, number of Cloud Volumes ONTAP systems, and the data services that you are using.
| RAM usage is too high | Increase the RAM of the agent VM in your cloud provider or on-premises, depending on where you installed it. Alternatively, create additional agents and distribute the workload across multiple agents. RAM utilization can vary based on your environment, ONTAP workloads, number of Cloud Volumes ONTAP systems, and the data services that you are using.


|===




== Stopping and starting the agent VM

If you need to, stop and start the agent VM using your cloud provider's console or standard on-premises procedures. 

link:concept-agents.html#agents-must-be-operational-at-all-times[Be aware that the Console agent must be operational at all times].


[[connect-linux-host]]
== Connect to the Linux VM

If you need to connect to the Linux VM that the agent runs on, use the connectivity options from your cloud provider.

AWS::
When you create the agent instance in AWS, provide an AWS access key and secret key. You can use this key pair to SSH to the instance. Use the user name 'ubuntu' for the EC2 Linux instance. For agents created prior to May 2023, use the user name 'ec2-user'.
+
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstances.html[AWS Docs: Connect to your Linux instance^]

Azure::
When you create the agent VM in Azure, you specify a user name and choose to authenticate with a password or SSH public key. Use the authentication method that you chose to connect to the VM.
+
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys#ssh-into-your-vm[Azure Docs: SSH into your VM^]

Google Cloud::
You can't specify an authentication method when you create an agent in Google Cloud. However, you can connect to the Linux VM instance using the Google Cloud Console or Google Cloud CLI (gcloud).
+
https://cloud.google.com/compute/docs/instances/connecting-to-instance[Google Cloud Docs: Connect to Linux VMs^]

