---
sidebar: sidebar
permalink: task-upgrade-agent.html
keywords: upgrade, manual upgrade, agent upgrade, manual agent upgrade, upgrade agent manually, private mode upgrade, offline upgrade, upgrade private mode, connector upgrade, agent upgrade
summary: The Console agent is automatically upgraded when it has outbound connectivity. If your Console agent does not have outbound connectivity, you can manually upgrade it (such as with private mode).
---

= Manage Console agent upgrades
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

The Console agent is automatically upgraded when it has outbound connectivity. If your Console agent does not have outbound connectivity, you can manually upgrade it (such as with private mode).


== Upgrade the Console agent

The Console agent needs to restart during the upgrade process so the NetApp Console will be unavailable during the upgrade.

.Steps

. Download the Console agent software from the https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab[NetApp Support Site^].

. Copy the installer to the Linux host.

. Assign permissions to run the script.
+
[source,cli]
----
chmod +x /path/NetApp-Console-Agent-Offline-<version>
----
+
Where <version> is the version of the Console agent that you downloaded.

. Run the installation script:
+
[source,cli]
----
sudo /path/NetApp-Console-Agent-Offline-<version>
----
+
Where <version> is the version of the agent that you downloaded.

. After the upgrade is complete, you can verify the agent's version by going to *Administration > Support > Agents*.
