---
sidebar: sidebar
permalink: task-quick-start-private-mode.html
keywords: private mode quick start, quick start, aws top secret cloud, aws secret cloud, secret cloud, top secret cloud, bluexp legacy, bluexp
summary: Private mode is typically used with on-premises environments that have no internet connection and with secure cloud regions, which includes AWS Secret Cloud, AWS Top Secret Cloud, and Azure IL6. Private mode is not yet available with the NetApp Console. NetApp continues to support these environments with the BlueXP legacy interface. link:<doc link to PDF>
---

= Getting started workflow (BlueXP private mode)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

BlueXP private mode (legacy BlueXP interface) is typically used with on-premises environments that have no internet connection and with secure cloud regions, which includes AWS Secret Cloud, AWS Top Secret Cloud, and Azure IL6. NetApp continues to support these environments with the legacy BlueXP interface. 

link:media/BlueXP-Private-Mode-legacy-interface.pdf[PDF documentation for BlueXP private mode^]


== Features and data services supported with private mode

The following table can help you quickly identify which BlueXP services and features are supported private mode.

Note that some services might be supported with limitations. 

[options="header",cols="19,27,27"]
|===

| Product area
| BlueXP service or feature
| Private mode

.10+| *Working environments*

This portion of the table lists support for working environment management from the BlueXP canvas. It does not indicate the supported backup destinations for BlueXP backup and recovery.
| Amazon FSx for ONTAP  | No
| Amazon S3  | No
| Azure Blob | No
| Azure NetApp Files | No 
| Cloud Volumes ONTAP | Yes 
| Google Cloud NetApp Volumes  | No
| Google Cloud Storage  | No
| On-premises ONTAP clusters | Yes
| E-Series | No
| StorageGRID | No 

.15+| *Services*
| Alerts  | No
| Backup and recovery 
| Yes

https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-journey.html#support-for-sites-with-no-internet-connectivity[View the list of supported backup destinations for ONTAP volume data^]
| Classification | Yes
| Copy and sync | No
| Digital advisor | No 
| Digital wallet  | Yes
| Disaster recovery  | No
| Economic efficiency  | No
| Ransomware Resilience  | No
| Replication  | Yes
| Software updates | No
| Sustainability | No
| Tiering | No
| Volume caching | No
| Workload factory | No

.8+| *Features*

| Identity and access management | Yes 
| Credentials  | Yes 
| Federation  | No 
| Multi-factor authentication  | No 
| NSS accounts  | No 
| Notifications  | No 
| Search  | No 
| Timeline | Yes 

|===

