---
sidebar: sidebar
permalink: task-logging-in.html
keywords: logging in, log in, sign in, signing in, cloud central, netapp cloud central, user account, federated, federation, federated login, federation login, login with netapp, log in with netapp, sign up, create account
summary: How you log in to the NetApp Console depends on which deployment mode that you're using.
---

= Log in to the NetApp Console
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
How you log in to the NetApp Console depends on which deployment mode that you're using.

You are automatically logged out after 24 hours or if you close your browser.


link:concept-modes.html[Learn about Console deployment modes].

// start tabbed area

[role="tabbed-block"]
====

.Standard mode
--
After you sign up to the NetApp Console, you can log in from the web-based console to start managing your data and storage infrastructure.

.About this task

You can log in to the NetApp Console using one of the following options:

* Your existing NetApp Support Site (NSS) credentials
* A NetApp Console account using your email address and a password
* A federated connection
+
You can use single sign-on to log in using credentials from your corporate directory (federated identity). link:concept-federation.html[Learn how to set up identity federation].

.Steps

. Open a web browser and go to the https://console.netapp.com[NetApp Console]

. On the *Log in* page, enter the email address that's associated with your login.

. Depending on the authentication method associated with your login, you'll be prompted to enter your credentials:
+
* NetApp cloud credentials: Enter your password
* Federated user: Enter your federated identity credentials
* NetApp Support Site account: Enter your NetApp Support Site credentials

.Result

You're now logged in and can start using to manage your hybrid multi-cloud infrastructure.
--

.Restricted mode
--
When you use the Console in restricted mode, you need to log in to the the Console from the user interface that runs locally on the agent.

.About this task

The Console supports logging in with one of the following options when in restricted mode:

* A NetApp Console login using your email address and a password
* A federated connection
+
You can use single sign-on to log in using credentials from your corporate directory (federated identity). link:concept-federation.html[Learn how to use identity federation].

.Steps

. Open a web browser and enter the IP address where the agent is installed.

. Enter your user name and password to log in.


--


====

// end tabbed area