---
sidebar: sidebar
permalink: task-maintain-agents.html
keywords: agent operating system, agent maintenance, vm maintenance, os updates, operating system updates, stop agent, restart agent, notifications, agent health, agent disk space, agent cpu usage, agent ram usage, agent vm, agent ip address, agent uri, connector, connector health
summary: Maintaining the operating system on the agent host is your responsibility. For example, you should apply security updates to the operating system on the Console agent host by following your company's standard procedures for operating system distribution.
---

= Maintain the Console agent VM and operating system 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Maintaining the operating system on the Console agent host is your (the customer's) responsibility. For example, you (the customer) should apply security updates to the operating system on the agent host by following your company's standard procedures for operating system distribution.

TIP: If you have an existing agent, you should be aware of link:reference-connector-operating-system-changes.html[changes to supported Linux operating systems].

== Operating system patches and the agent

Apply OS security patches without stopping agent host services.

== VM or instance type

If you create a Console agent from the Console, it deploys a VM instance in your cloud provider with a default configuration. After you create the agent, don't switch to a smaller VM instance with less CPU or RAM.

The following table lists the CPU and RAM requirements:

include::_include/os-reqs.adoc[tag=cpu-ram]

link:reference-connector-default-config.html[Learn about the default configuration for the agent].

[[monitor-disk-space]]
== Monitor the agent

The Console notifies you when the agent VM is unhealthy, including disk space, RAM, and CPU issues. Monitor these notifications in the Notifications Center within the Console or configure email notifications. Occasional increases in disk space, memory, or CPU usage are normal, but if it happens frequently, you should take steps to resolve.

For example, the Console notifies you when an agent resource (CPU, RAM, or disk space) exceeds 90% of its total capacity for 30 consecutive minutes. Afterwards, if the resource usage drops below that threshold, the notification displays as resolved (green) in the Notifications Center.


NOTE: Work with NetApp support if you have questions about modifying your agent VM.


link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#notification-center[Learn more.^]

[cols=2*,options="header",cols="47,47",width="95%"]
|===

| Notification
| Action needed

| Disk space is too high | link:https://kb.netapp.com/Cloud/BlueXP/Cloud_Manager/How_to_resolve_disk_space_issues_on_BlueXP_connector_VM[Review the NetApp Knowledge Base article^].
| CPU usage is too high | Increase the CPU size of the agent VM in your cloud provider or on-premises, depending on where you installed it. Alternatively, create additional agents and distribute the workload across multiple agents. RAM utilization can vary based on your environment, ONTAP workloads, number of Cloud Volumes ONTAP systems, and the data services that you are using.
| RAM usage is too high | Increase the RAM of the agent VM in your cloud provider or on-premises, depending on where you installed it. Alternatively, create additional agents and distribute the workload across multiple agents. RAM utilization can vary based on your environment, ONTAP workloads, number of Cloud Volumes ONTAP systems, and the data services that you are using.


|===




== Stopping and starting the agent VM

If you need to, stop and start the agent VM using your cloud provider's console or standard on-premises procedures. 

link:concept-connectors.html#connectors-must-be-operational-at-all-times[Be aware that the Console agent must be operational at all times].


[[connect-linux-host]]
== Connect to the Linux VM

If you need to connect to the Linux VM that the agent runs on, use the connectivity options from your cloud provider.

AWS::
When you create the agent instance in AWS, provide an AWS access key and secret key. You can use this key pair to SSH to the instance. Use the user name 'ubuntu' for the EC2 Linux instance. For agents created prior to May 2023, use the user name 'ec2-user'.
+
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstances.html[AWS Docs: Connect to your Linux instance^]

Azure::
When you create the agent VM in Azure, you specify a user name and choose to authenticate with a password or SSH public key. Use the authentication method that you chose to connect to the VM.
+
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys#ssh-into-your-vm[Azure Docs: SSH into your VM^]

Google Cloud::
You can't specify an authentication method when you create an agent in Google Cloud. However, you can connect to the Linux VM instance using the Google Cloud Console or Google Cloud CLI (gcloud).
+
https://cloud.google.com/compute/docs/instances/connecting-to-instance[Google Cloud Docs: Connect to Linux VMs^]

== Change the IP address for an agent

You can change the internal and public IP addresses of the agent instance assigned by your cloud provider if needed.

.Steps

. Follow the instructions from your cloud provider to change the local IP address or public IP address (or both) for the agent instance.

. Restart the agent instance to register a new public IP address with the Console.

. If you changed the private IP address, update the backup location for Cloud Volumes ONTAP configuration files so that the backups are being sent to the new private IP address on the agent.
+
Update the backup location for each Cloud Volumes ONTAP system.

.. From the Cloud Volumes ONTAP CLI, set the privilege level to advanced:
[source,cli]
set -privilege advanced

.. Run the following command to display the current backup target:
[source,cli]
system configuration backup settings show

.. Run the following command to update the IP address for the backup target:
[source,cli]
system configuration backup settings modify -destination <target-location>

== Edit an agent's URIs

You can add and remove the Uniform Resource Identifier (URI) for an agent.

.Steps

. Select *Administration > Agents*.

. On the *Overview* page, select the action menu for a Console agent and select *Edit agent*.
+
The Console agent must be active to edit it.

. Expand the *Agent URIs* bar to view agent URIs.


. Add and remove URIs and then select *Apply*.