---
sidebar: sidebar
permalink: task-organization-verify.html
keywords: adding, creating, netapp support site account, nss, update account, update nss account, update nss credentials, delete nss account, remove nss account, change working environment, working environment nss, digital wallet, license, change system, system nss, licenses and subscriptions
summary: Associate a NetApp Support Site account with your NetApp Console organization to enable key workflows for Cloud Volumes ONTAP. These NSS credentials are associated with the entire organization.
---

= Verify your NetApp Console organization
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
If you are using Digital Advisor, you need to verify your Console organization if your company has multiple business accounts with NetApp. Digital advisor may display multiple NetApp accounts that are not related to your Console organization. To ensure that you see only resources associated with your Console organization, you can verify the business ID that you want to associate with your Console organization.

The Console also supports associating one NSS account per user account. link:task-manage-user-credentials.html[Learn how to manage user-level credentials].

== Before you begin
You must have the Organization admin role to verify your organization and your user must also be associated with an NetApp Support Site (NSS) account. link:task-adding-nss-accounts[Learn how to associate your NSS account].

NOTE: If your company has only one business account and your user is associated with a NetApp Support Site account, your organization is verified automatically.


== Verify your organization



.Steps

. If your user has access to more than one organization, select the organization you want to verify from the Organization drop-down menu.

. In *Administration >  Identity and access*.

. Select *Organization*.


