---
sidebar: sidebar
permalink: task-iam-manage-members-permissions.html
keywords: user, service account, member, role, permissions, organization, project, folder, iam, identity and access management
summary: Manage your organization's members to provide permissions across different levels of your organization's resource hierarchy.
---

= Grant users access to NetApp Console resources
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Within the Console, you can add users and service accounts to your organization and assign them one or more roles across your resource hierarchy. A _role_ contains a set of permissions that enables a member (user or service account) to perform specific actions at a specific level of the resource hierarchy. 

.Required access roles
Super admin, Org admin, or Folder or project admin (for folders and projects that they are administering). Link:reference-iam-predefined-roles.html[Learn about access roles].

== Understand how access is granted in NetApp Console           
NetApp Console uses a role-based access control (RBAC) model to manage user permissions. You can assign predefined roles to members individually or through federated groups. You can add and assign roles to service accounts. Each role defines what actions a member can perform at the associated resources.

Note the following about granting access in NetApp Console:

* All users must first sign up for the NetApp Console before they can be granted access to resources
* You must explicitly assign a role to each user in the Console before they can access resources, even if they are members of a federated group that has been assigned a role.   
* You can add service accounts directly from the Console and assign them roles.



[#add-members]
== Add members to your organization

NetApp Console supports three types of members: user accounts, service accounts, and federated groups. Applications use service accounts to do API tasks automatically. People use user accounts to log in and manage resources.

Users must sign up for the NetApp Console before you can add them to an organization or assign them a role. You create service accounts directly from the Console.

All members must have at least one role explicitly assigned to them in order to access resources.



=== Add a user account

Users sign up for the NetApp Console, but an Org admin or Folder or project admin must add them to an organization, folder, or project so they can access resources.

.Before you begin:
The user must have already signed up for the NetApp Console. If they haven't signed up yet, direct them to link:task-sign-up-saas.html[sign up for the NetApp Console.^

.Steps

. Select *Administration > Identity and access*.

. Select *Members*.

. Select *Add a member*.

. For *Member Type*, keep *User* selected.
. For *User's email*, enter the user's email address that is associated with the login that they created.
. Use the *Select an organization, folder, or project* section to choose the level of your resource hierarchy that the member should have permissions for.

+ 
Note the following:

** You can only select from the folders and projects for which you have permissions.
** Selecting an organization or folder grants the member permissions to all its contents.
** You can only assign the *Organization admin* role at the organization level.

. *Select a category* then select a *Role* that provides the member with permissions for the resources that are associated with the organization, folder, or project that you selected.

+
link:reference-iam-predefined-roles.html[Learn about access roles].

. To give access to more folders, projects, or roles, select *Add role*, choose the folder, project, or role category, and select a role.

. Select *Add*. 
+
The Console emails instructions to the user.



[[service-account]]
=== Add a service account 
Service accounts let you do tasks automatically and connect with Console APIs safely. Choose client ID and secret for simple setups, or JWT (JSON Web Token) for stronger security in automated or cloud-native environments. Pick the method that fits your security needs.

.Before you begin:
For JWT authentication, prepare your public key or certificate.


.Steps

. Select *Administration > Identity and access*.

. Select *Members*.

. Select *Add a member*.

. For *Member Type*, select *Service account*.

. Enter a name for the service account.


. If you want to use JWT authentication, select *Use private key JWT authentication* and upload your public RSA key or certificate. Skip this step if you want to use a client ID and secret instead.

+  
Your X.509 certificate. It must be in  PEM, CRT, or CER format.

+
.. Set up expiry notifications for your certificate. Choose between seven days or 30 days. Expiry notifications are emailed and shown in the Console to users with the Super admin or Org admin role.


. Use the *Select an organization, folder, or project* section to choose the level of your resource hierarchy that the member should have permissions for.
+
Note the following:
+
** You can only select from the folders and projects for which you have permissions.
** Selecting an organization or folder grants the member permissions to all its contents.
** You can only assign the *Organization admin* role at the organization level.

. Select a *Category* then select a *Role* that gives the member permissions for the resources in the organization, folder, or project you selected.

+
link:reference-iam-predefined-roles.html[Learn about access roles].

. To give access to more folders, projects, or roles, select *Add role*, choose the folder, project, or role category, and select a role.


. If you didn't choose to use JWT authentication, download or copy the client ID and client secret. +
The Console shows the client secret only once. Copy it securely; you can recreate it later if needed.

. If you chose JWT authentication, download or copy the client ID and JWT audience. This information is shown only once and cannot be retrieved later.

. Select *Close*.

== Add a federated group to your organization

You can add a federated group from your identity provider (IdP) to your organization. Members of the federated group inherit the roles that you assign to the group in the Console.

.Before you begin:
Ensure the following before adding a federated group:
* You must have already set up federation between your IdP and the Console. link:concept-federation.html[Learn how to set up federation.^]
* The group must already exist in your IdP.
* You must know the exact name of the group in your IdP.
* Users belonging to the group must have already signed up for the NetApp Console and been explicitly assigned a role in the Console.

.Steps
. Select *Administration > Identity and access*.
. Select *Members*.
. Select *Add a member*.
. For *Member Type*, select *Federated Group*.
. Select the federation of which the group is a member
. For *Group name*, enter the exact name of the group in your IdP.
. Use the *Select an organization, folder, or project* section to choose the level of your resource hierarchy that the member should have permissions for.
+
Note the following:
+
** You can only select from the folders and projects for which you have permissions.
** Selecting an organization or folder grants the member permissions to all its contents.
** You can only assign the *Organization admin* role at the organization level.

. Select a *Category* then select a *Role* that gives the member permissions for the resources in the organization, folder, or project you selected.

+
link:reference-iam-predefined-roles.html[Learn about access roles].

. To give access to more folders, projects, or roles, select *Add role*, choose the folder, project, or role category, and select a role.



























== Related information

* link:concept-identity-and-access-management.html[Learn about identity and access management in NetApp Console]
* link:task-iam-get-started.html[Get started with identity and access]
* link:reference-iam-predefined-roles.html[NetApp Console access roles]
* https://docs.netapp.com/us-en/console-automation/tenancyv4/overview.html[Learn about the API for identity and access^]