---
sidebar: sidebar
permalink: task-federation-group-based-access.html
keywords: federation, BlueXP, identity provider, IdP, single sign-on, SSO, verified domain, credentials, certificate, client secret, update, manage federations, security, compliance, user access, productivity, account management, authentication, access control, business continuity
summary: After you've added a federated connection, you can manage it in the NetApp Console. You can view the status of the connection, enable or disable it as needed.
---

= Assign roles to federated groups in NetApp Console
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Assign NetApp Console roles to specific IdP groups directly from NetApp Console, granting each Console user in the group the same roles.

With group-based access control, you can use IdP-defined user groups to assign permissions in NetApp Console. Roles are automatically assigned or revoked based on group membership in your identity provider (IdP).
View and manage group-based access control from the *Federation* page in the NetApp Console.

NOTE: You must have already link:concept-federation.html[added a federated connection] to use group-based access control.

== Prerequisites

User must have already signed up for a NetApp Console account.
You must have already added the user to your NetApp organization and assigned the user a role. Each user must be assigned at least one role directly in NetApp Console before group-based access control can take effect for that user.

== Add a federated group to your organization

. Select *Administration > Identity and access*.
. Select the *Members* tab.
. Select the *Federated groups* tab and then select *Add federated group*.

. Select the name of the federation that contains the group you want to add. 

. In the *Federated group* field, enter the exact name of the group as it appears in your IdP. This field is case-sensitive.

. Assign a role to the group. Each user in the group will inherit the assigned role(s) when they sign in to NetApp Console.
+
NOTE: You can assign multiple roles to a group by repeating these steps.

.. Select the organization, project or folder level where you want to assign the role. Mark the check box and then select *Accept*.
.. Select the category of the role you want to assign to the group. 

.. Select the specific role or roles you want to assign to the group and then select *Accept*.

. Select *Add* to add the federated group to your organization.




