


== BlueXP is now NetApp Console

The NetApp Console, built on the enhanced and restructured BlueXP foundation, provides centralized management of NetApp storage and NetApp Data Services across on-premises and cloud environments at enterprise grade—delivering real-time insights, faster workflows, and simplified administration, that is highly secure and compliant.

For a complete list of the navigational and terminology changes in the new NetApp Console, see link:https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#console-intro[What's new in NetApp Console].

== Console agent 4.0.0

This release of the Console agent includes security improvements, bug fixes and the following new features.

The 4.0.0 release is available for standard mode and restricted mode.

=== Consolidation and reduction of required network endpoints
NetApp has reduced the required network endpoints for the Console and Console agents, enhancing security and simplifying deployment. Importantly, all deployments prior to version 4.0.0 continue to be fully supported. While previous endpoints remain available for existing agents, NetApp strongly recommends updating firewall rules to the current endpoints after confirming successful agent upgrades.

* link:https://docs.netapp.com/us-en/console-setup-admin/reference-networking-saas-console-previous.html#update-endpoint-list[Learn how to update your endpoint list].
* link:https://docs.netapp.com/us-en/console-setup-admin/reference-networking-saas-console.html[Learn more about required endpoints.]

=== Support for VCenter deployment of Console agents
You can deploy Console agents in VMware environments using an OVA file. The OVA file includes a pre-configured VM image with Console agent software and settings to connect to the NetApp Console. A file download or URL deployment is available directly from the NetApp Console. link:https://docs.netapp.com/us-en/console-setup-admin/task-install-agent-on-prem-ova.html[Learn how to deploy a Console agent in VMware environments.]

The Console agent OVA for VMware offers a pre-configured VM image for quick deployment.

=== Validation reports for failed agent deployments
When you deploy a Console agent from the NetApp Console, you now have the option to validate the agent configuration. If the Console fails to deploy the agent, it provides a downloadable report to help you troubleshoot. 

=== Improved troubleshooting for Console agents
The Console agent has improved error messages that help you better understand issues. link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-connector.html[Learn how to troubleshoot Console agents.]

== NetApp Console

NetApp Console administration includes the following new features:

=== Home page dashboard
The NetApp Console's Home page dashboard provides real-time visibility into storage infrastructure with metrics for health, capacity, license status, and data services. link:https://docs.netapp.com/us-en/console-setup-admin/task-dashboard.html[Learn more about the Home page.]

=== NetApp assistant
New users with the Organization admin role can use the NetApp assistant to configure the Console, including adding an agent, linking a NetApp Support account, and adding a storage system.
link:https://docs.netapp.com/us-en/console-setup-admin/task-console-assistant.html[Learn about the NetApp assistant.]



=== Service account authentication

The NetApp Console supports service account authentication using either a system-generated client ID and secret or customer-managed JWTs, allowing organizations to select the approach that best fits their security requirements and integration workflows. Private Key JWT Client Authentication uses asymmetric cryptography, providing stronger security than traditional client ID and secret methods. Private Key JWT Client Authentication uses asymmetric cryptography, keeping the private key secure in the customer’s environment, reducing credential theft risks, and improving the security of your automation stack and client applications. link:https://docs.netapp.com/us-en/console-setup-admin/task-iam-manage-members-permissions.html#service-account[Learn how to add a service account.]

=== Session timeouts

The system logs out users after 24 hours or when they close their web browser.


=== Support for partnerships between organizations

You can create partnerships in the NetApp Console that let partners securely manage NetApp resources across organizational boundaries, making collaboration easier and security stronger. link:https://docs.netapp.com/us-en/console-setup-admin/task-partnerships-create.html[Learn how to manage partnerships].

=== Super admin and Super viewer roles
Added the *Super admin* and *Super viewer* roles. *Super admin* grants full management access to Console features, storage, and data services. *Super viewer* provides read-only visibility for auditors and stakeholders. These roles are useful for smaller teams of senior members where broad access is common. For improved security and auditability, organizations are encouraged to use *Super admin* access sparingly and assign fine-grained roles where possible. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html[Learn more about access roles.]

=== Additional role for Ransomware Resilience
Added the  *Ransomware Resilience user behavior admin* role and the *Ransomware Resilience user behavior viewer* role. These roles allow users to configure and view user behavior and analytics data, respectively. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html[Learn more about access roles.]

=== Removed support chat
NetApp has removed the support chat feature from the NetApp Console. Use the *Administration > Support* page to create and manage support cases.



















