

=== Console agent 4.2.0

The 4.2.0 release is available for standard mode and restricted mode.
This release of the Console agent includes security improvements, bug fixes, and the following features:

.Improved configuration checks for Console agents

* The Console agent now checks for deprecated endpoints when performing a configuration check. If you have not updated to the new endpoint list for 4.0.0 or higher, installations succeed if the system can reach the previous endpoint list. link:https://docs.netapp.com/us-en/console-setup-admin/reference-networking-saas-console-previous.html#update-endpoint-list[Learn more about the required endpoints for Console agents.^]

* Run configuration checks on installed Console agents from the Console or Agent maintenance console to verify connectivity and troubleshoot issues. link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html#verify-network-access[Learn how to run configuration checks on Console agents.^]



=== NetApp Console administration
This release includes the following:


.Ability to set notifications for expiring credentials

You can set notifications on expiring credentials for both service accounts and federations.Choose between seven days or 30 days. The Console shows notifications and emails them to users with the appropriate role. Org admins receive notifications for service accounts. Org admins, Federation admins, and Federation viewers receive notifications for federations.


.Local logins are not available after enabling federation
After you enable federation for a Console organization, users can no longer use local logins and instead are directed to federation logins.


