After you install and set up the Console agent, add your cloud credentials so that the Console agent has the required permissions to perform actions in AWS or Azure.

// start tabbed area

[role="tabbed-block"]
====

.AWS
--
.Before you begin

If you just created these AWS credentials, they may take a few minutes to become available. Wait a few minutes before you add the credentials to the Console.

.Steps

include::_include/provide-permissions-access-key.adoc[]

You can now go to the https://console.netapp.com[NetApp Console^] to start using the Console agent.
--

.Azure
--

.Before you begin

If you just created these Azure credentials, they may take a few minutes to become available. Wait a few minutes before you add the credentials the Console agent.

.Steps

include::_include/azure-provide-permissions-service-principal.adoc[]

.Result

THe Console agent now has the permissions that it needs to perform actions in Azure on your behalf. You can now go to the https://console.netapp.com[NetApp Console^] to start using the Console agent.
--

====

// end tabbed area