After you install and set up the Console agent, add your cloud credentials so that the Console agent has the required permissions to perform actions in AWS or Azure.

// start tabbed area

[role="tabbed-block"]
====

.AWS
--
.Before you begin

If you just created these AWS credentials, they may take a few minutes to become available. Wait a few minutes before you add the credentials to the Console.

.Steps

. Select *Administration > Credentials*.

. Select *Organization credentials*.

. Select *Add Credentials* and follow the steps in the wizard.

.. *Credentials Location*: Select *Amazon Web Services > Agent.

.. *Define Credentials*: Enter an AWS access key and secret key.

.. *Marketplace Subscription*: Associate a Marketplace subscription with these credentials by subscribing now or by selecting an existing subscription.

.. *Review*: Confirm the details about the new credentials and select *Add*.

You can now go to the https://console.netapp.com[NetApp Console^] to start using the Console agent.
--

.Azure
--

.Before you begin

If you just created these Azure credentials, they may take a few minutes to become available. Wait a few minutes before you add the credentials the Console agent.

.Steps
. Select *Administration > Credentials*.

. Select *Add Credentials* and follow the steps in the wizard.

.. *Credentials Location*: Select *Microsoft Azure > Agent*.

.. *Define Credentials*: Enter information about the Microsoft Entra service principal that grants the required permissions:
+
* Application (client) ID
* Directory (tenant) ID
* Client Secret

.. *Marketplace Subscription*: Associate a Marketplace subscription with these credentials by subscribing now or by selecting an existing subscription.

.. *Review*: Confirm the details about the new credentials and select *Add*.

.Result

THe Console agent now has the permissions that it needs to perform actions in Azure on your behalf. You can now go to the https://console.netapp.com[NetApp Console^] to start using the Console agent.
--

====

// end tabbed area