//tag::before[]
.Before you begin

You should have the following:

* Root privileges to install the Console agent.

* Details about a proxy server, if a proxy is required for internet access from the Console agent.
+
You have the option to configure a proxy server after installation but doing so requires restarting the Console agent.


* A CA-signed certificate, if the proxy server uses HTTPS or if the proxy is an intercepting proxy.

NOTE: You cannot set a certificate for a transparent proxy server when manually installing the Console agent. If you need to set a certificate for a transparent proxy server, you must use the Maintenance Console after installation. Learn more about the link:reference-connector-maint-console.html[Agent Maintenance Console].
//end::before[]

//tag::about[]
.About this task

The installer that is available on the NetApp Support Site might be an earlier version. After installation, the Console agent automatically updates itself if a new version is available.
//end::about[]

//tag::main-steps[]
.Steps

. If the _http_proxy_ or _https_proxy_ system variables are set on the host, remove them:
+
[source,cli]
unset http_proxy
unset https_proxy
+
If you don't remove these system variables, the installation fails.

. Download the Console agent software from the https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab[NetApp Support Site^], and then copy it to the Linux host.
+
You should download the "online" agent installer that's meant for use in your network or in the cloud. 

. Assign permissions to run the script.
+
[source,cli]
chmod +x Netapp_Console_Agent_Cloud_<version>

+
Where <version> is the version of the Console agent that you downloaded.

. Run the installation script.
+
[source,cli]
 ./Netapp_Console_Agent_Cloud_<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
+
You'll need to add proxy information if your network requires a proxy for internet access. You can add either a transparent or explicit proxy. The --proxy and --cacert parameters are optional and you won't be prompted to add them. If you have a proxy server, you will need to enter the parameters as shown. 
+
Here is an example configuring an explicit proxy server with a CA-signed certificate:
+
[source,cli]
 ./Netapp_Console_Agent_Cloud_v4.0.0--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
+
`--proxy` configures the Console agent to use an HTTP or HTTPS proxy server using one of the following formats:
+
* \http://address:port
* \http://user-name:password@address:port
* \http://domain-name%92user-name:password@address:port
* \https://address:port
* \https://user-name:password@address:port
* \https://domain-name%92user-name:password@address:port
+
Note the following:
+
** The user can be a local user or domain user.
** For a domain user, you must use the ASCII code for a \ as shown above.
** The Console agent doesn't support user names or passwords that include the @ character.
** If the password includes any of the following special characters, you must escape that special character by prepending it with a backslash: & or !
+
For example:
+
\http://bxpproxyuser:netapp1\!@address:3128

+
`--cacert` specifies a CA-signed certificate to use for HTTPS access between Console agent and the proxy server. This parameter is required for HTTPS proxy servers, intercepting proxy servers, and transparent proxy servers.

+
Here is an example configuring a transparent proxy server. When you configure a transparent proxy, you don't need to define the proxy server. You only add a CA-signed certificate to your Console agent host:

+
[source,cli]
 ./Netapp_Console_Agent_Cloud_v4.0.0 --cacert /tmp/cacert/certificate.cer

. If you used Podman, you'll need to adjust the aardvark-dns port.
.. SSH to the Console agent virtual machine.
.. Open podman _/usr/share/containers/containers.conf_ file and modify the chosen port for Aardvark DNS service. For example, change it to 54.
+
[source, cli]
vi /usr/share/containers/containers.conf
...
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
...
Esc:wq
+
.. Reboot the Console agent virtual machine.
//end::main-steps[]

//tag::standard-mode-steps-for-cloud[]
. Wait for the installation to complete.
+
At the end of the installation, the Console agent service (occm) restarts twice if you specified a proxy server.



. Open a web browser from a host that has a connection to the Console agent virtual machine and enter the following URL:
+
https://_ipaddress_

. After you log in, set up the Console agent:
.. Specify the organization to associate with the Console agent.
.. Enter a name for the system.
.. Under *Are you running in a secured environment?* keep restricted mode disabled.
+
You should keep restricted mode disabled because these steps describe how to use the Console in standard mode. You should enable restricted mode only if you have a secure environment and want to disconnect this account from backend services. If that's the case, link:task-quick-start-restricted-mode.html[follow steps to get started with the NetApp Console in restricted mode].
.. Select *Let's start*.

//end::standard-mode-steps-for-cloud[]